-- Bootstrap and load lazy.nvim
require("user.lazy-bootstrap")

-- Setup lazy with plugin specifications
require("lazy").setup("user.lazy-plugins", {
  change_detection = {
    notify = false,
  },
})
require("user.nvim-tree")
require("user.cmp")
require("user.color_scheme")
require("user.comment")
require("user.dap")
require("user.gitsigns")
require("user.indent_blankline")
require("user.lsp_servers")
require("user.nvim-treesitter")
require("user.telescope")
require("user.formatter").config()
require("user.iron-vim")
require("user.neogit")
require("user.lualine")
require("user.toggleterm")
require("user.code_companion")
-- require("user.noice")
-- TODO: make it more autogenerated - something to do with 
-- commented out lines below - so i wouldn't have to modify the list
-- above each time i'm removing/adding plugins
-- Migrated to lazy.nvim - packer backup available in packer.lua.backup



-- local augroup = vim.api.nvim_create_augroup
-- local User = augroup('User', {})

-- local autocmd = vim.api.nvim_create_autocmd
-- local yank_group = augroup('HighlightYank', {})

-- function R(name)
--   require("plenary.reload").reload_module(name)
-- end

-- autocmd('TextYankPost', {
--     group = yank_group,
--     pattern = '*',
--     callback = function()
--         vim.highlight.on_yank({
--             higroup = 'IncSearch',
--             timeout = 40,
--        })
--    end,
-- })

-- autocmd({"BufWritePre"}, {
--    group = User,
--   pattern = "*",
--  command = [[%s/\s\+$//e]],
--})
